/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    'catalog-media': CatalogMedia;
    genres: Genre;
    studios: Studio;
    titles: Title;
    seasons: Season;
    episodes: Episode;
    voices: Voice;
    'rights-records': RightsRecord;
    'source-records': SourceRecord;
    'tenant-titles': TenantTitle;
    'editorial-collections': EditorialCollection;
    posts: Post;
    pages: Page;
    media: Media;
    redirects: Redirect;
    'audit-log': AuditLog;
    comments: Comment;
    'comment-reports': CommentReport;
    'import-jobs': ImportJob;
    'release-events': ReleaseEvent;
    'player-profiles': PlayerProfile;
    'site-settings': SiteSetting;
    navigation: Navigation;
    'home-layout': HomeLayout;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'catalog-media': CatalogMediaSelect<false> | CatalogMediaSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    studios: StudiosSelect<false> | StudiosSelect<true>;
    titles: TitlesSelect<false> | TitlesSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    voices: VoicesSelect<false> | VoicesSelect<true>;
    'rights-records': RightsRecordsSelect<false> | RightsRecordsSelect<true>;
    'source-records': SourceRecordsSelect<false> | SourceRecordsSelect<true>;
    'tenant-titles': TenantTitlesSelect<false> | TenantTitlesSelect<true>;
    'editorial-collections': EditorialCollectionsSelect<false> | EditorialCollectionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'comment-reports': CommentReportsSelect<false> | CommentReportsSelect<true>;
    'import-jobs': ImportJobsSelect<false> | ImportJobsSelect<true>;
    'release-events': ReleaseEventsSelect<false> | ReleaseEventsSelect<true>;
    'player-profiles': PlayerProfilesSelect<false> | PlayerProfilesSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'home-layout': HomeLayoutSelect<false> | HomeLayoutSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Каждый сайт — самостоятельный бренд, домен и SEO-политика.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Внутренний код: site_a, site_b, site_c. Не отображается посетителям.
   */
  slug: string;
  /**
   * Домен без схемы. По нему запрос сопоставляется с сайтом.
   */
  domain: string;
  seoProfile: 'catalog_authority' | 'release_pulse' | 'editorial_guide';
  theme: 'portal_light' | 'pulse' | 'editorial';
  /**
   * Пока выключено, сайт отдаёт noindex целиком. Включается только после проверки контента и SEO.
   */
  indexingEnabled?: boolean | null;
  allowGuestComments?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super_admin' | 'site_admin' | 'editor' | 'moderator' | 'analyst';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Постеры и кадры, общие для всех сайтов. Хранятся отдельно от медиатеки сайта: общий тайтл не может ссылаться на файл одного сайта, иначе он утёк бы на остальные.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-media".
 */
export interface CatalogMedia {
  id: number;
  /**
   * Обязателен: без alt изображение не публикуется.
   */
  alt: string;
  /**
   * Без подтверждённых прав изображение не попадает в публикацию.
   */
  rightsRecord: number | RightsRecord;
  source?: ('manual' | 'provider_api' | 'import_file') | null;
  sourceRef?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rights-records".
 */
export interface RightsRecord {
  id: number;
  label: string;
  holder: string;
  contractRef: string;
  territory?: string | null;
  validUntil?: string | null;
  /**
   * Без этого флага тайтл не публикуется ни на одном сайте.
   */
  allowsPublication?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studios".
 */
export interface Studio {
  id: number;
  name: string;
  slug: string;
  source?: ('manual' | 'provider_api' | 'import_file') | null;
  sourceRef?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Проверенные факты о тайтле. Тексты и SEO конкретного сайта — в разделе «Публикации сайта».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "titles".
 */
export interface Title {
  id: number;
  primaryName: string;
  englishName?: string | null;
  originalName?: string | null;
  alternativeNames?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  kind: 'series' | 'movie' | 'ova';
  status: 'ongoing' | 'completed' | 'announced';
  year?: number | null;
  /**
   * Факты из источника. Редакционный текст сайта пишется отдельно и не выдаётся за оригинальный.
   */
  factualSynopsis?: string | null;
  /**
   * Исчезнувший из источника материал получает явное состояние. Подменять его другим тайтлом запрещено.
   */
  availability: 'available' | 'unavailable' | 'withdrawn';
  genres?: (number | Genre)[] | null;
  studios?: (number | Studio)[] | null;
  poster?: (number | null) | CatalogMedia;
  playbackAggregator?: ('kp' | 'mali' | 'mdl') | null;
  playbackTitleId?: string | null;
  rightsRecord?: (number | null) | RightsRecord;
  /**
   * Только реальные связи. «Похожее» не придумывается.
   */
  relatedTitles?: (number | Title)[] | null;
  source?: ('manual' | 'provider_api' | 'import_file') | null;
  sourceRef?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  title: number | Title;
  number: number;
  label?: string | null;
  source?: ('manual' | 'provider_api' | 'import_file') | null;
  sourceRef?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: number;
  season: number | Season;
  number: number;
  label?: string | null;
  /**
   * Только известная дата. Пустое поле лучше выдуманного.
   */
  airedAt?: string | null;
  /**
   * Снимается автоматически, если провайдер сообщил об отсутствии данных.
   */
  playbackAvailable?: boolean | null;
  source?: ('manual' | 'provider_api' | 'import_file') | null;
  sourceRef?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Справочник озвучек. Значения используются в атрибутах плеера only-voice / priority-voice строго в том виде, в каком их принимает документированный контракт плеера.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voices".
 */
export interface Voice {
  id: number;
  name: string;
  slug: string;
  /**
   * Заполняется только значением, подтверждённым документацией или ответом провайдера. Пусто = озвучка не передаётся в плеер (BLOCKED_INPUT для сценариев, где она требуется).
   */
  playerValue?: string | null;
  source?: ('manual' | 'provider_api' | 'import_file') | null;
  sourceRef?: string | null;
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-records".
 */
export interface SourceRecord {
  id: number;
  label: string;
  kind: 'provider_api' | 'file' | 'manual';
  reference: string;
  sha256?: string | null;
  retrievedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Как конкретный тайтл представлен на этом сайте: URL, редакционный текст, SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-titles".
 */
export interface TenantTitle {
  id: number;
  tenant?: (number | null) | Tenant;
  title: number | Title;
  slug: string;
  /**
   * Оригинальный текст редакции этого сайта. Не копия описания провайдера.
   */
  editorialIntro?: string | null;
  editorialAuthor?: (number | null) | User;
  highlight?: boolean | null;
  /**
   * Если пусто — собирается по шаблону сайта из фактических данных.
   */
  seoTitle?: string | null;
  /**
   * Описывает то, что реально видно на странице. Не выдумывать факты.
   */
  seoDescription?: string | null;
  robots?: ('inherit' | 'index' | 'noindex') | null;
  /**
   * Пусто = self-canonical. Заполняется только при документированном решении.
   */
  canonicalOverride?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Загружайте только материалы с подтверждёнными правами.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Обязателен: без alt материал не публикуется.
   */
  alt: string;
  rightsRecord?: (number | null) | RightsRecord;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-collections".
 */
export interface EditorialCollection {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  /**
   * Подборка без собственного текста не индексируется.
   */
  intro?: string | null;
  items?: (number | TenantTitle)[] | null;
  /**
   * Если пусто — собирается по шаблону сайта из фактических данных.
   */
  seoTitle?: string | null;
  /**
   * Описывает то, что реально видно на странице. Не выдумывать факты.
   */
  seoDescription?: string | null;
  robots?: ('inherit' | 'index' | 'noindex') | null;
  /**
   * Пусто = self-canonical. Заполняется только при документированном решении.
   */
  canonicalOverride?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  headline: string;
  slug: string;
  lead?: string | null;
  body?: string | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  cover?: (number | null) | Media;
  /**
   * Если пусто — собирается по шаблону сайта из фактических данных.
   */
  seoTitle?: string | null;
  /**
   * Описывает то, что реально видно на странице. Не выдумывать факты.
   */
  seoDescription?: string | null;
  robots?: ('inherit' | 'index' | 'noindex') | null;
  /**
   * Пусто = self-canonical. Заполняется только при документированном решении.
   */
  canonicalOverride?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  body?: string | null;
  /**
   * Если пусто — собирается по шаблону сайта из фактических данных.
   */
  seoTitle?: string | null;
  /**
   * Описывает то, что реально видно на странице. Не выдумывать факты.
   */
  seoDescription?: string | null;
  robots?: ('inherit' | 'index' | 'noindex') | null;
  /**
   * Пусто = self-canonical. Заполняется только при документированном решении.
   */
  canonicalOverride?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  tenant?: (number | null) | Tenant;
  from: string;
  to: string;
  status?: ('301' | '410') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  tenant?: (number | null) | Tenant;
  summary: string;
  actor?: (number | null) | User;
  collection?: string | null;
  documentId?: string | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Очередь модерации: новые комментарии ждут решения и не видны на сайте.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  tenant?: (number | null) | Tenant;
  targetType: 'title' | 'season' | 'episode' | 'post';
  targetId: string;
  targetUrl?: string | null;
  author?: (number | null) | User;
  guestName?: string | null;
  guestEmail?: string | null;
  parent?: (number | null) | Comment;
  root?: (number | null) | Comment;
  depth?: number | null;
  body: string;
  excerpt?: string | null;
  status: 'pending' | 'published' | 'rejected' | 'spam' | 'deleted';
  moderator?: (number | null) | User;
  moderatedAt?: string | null;
  moderatorNote?: string | null;
  reportCount?: number | null;
  /**
   * Отпечаток отправки. Защищает от дублей при повторе запроса.
   */
  submissionKey?: string | null;
  /**
   * Хэш отправителя для антифлуда. Исходный IP не хранится.
   */
  authorKey?: string | null;
  submissionMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comment-reports".
 */
export interface CommentReport {
  id: number;
  tenant?: (number | null) | Tenant;
  comment: number | Comment;
  reason: 'spam' | 'abuse' | 'spoiler' | 'other';
  note?: string | null;
  resolved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Журнал обращений к Content API провайдера. Показывает, что именно было запрошено, сколько записей создано/обновлено/пропущено и в каком режиме (mock или live).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs".
 */
export interface ImportJob {
  id: number;
  reference: string;
  /**
   * Production технически отвергает mock: проверка выполняется в адаптере, а не на словах.
   */
  mode: 'mock' | 'live';
  status: 'running' | 'succeeded' | 'failed' | 'blocked_input' | 'blocked_content_rights' | 'blocked_access';
  /**
   * sha256 нормализованных параметров запроса. Повторный импорт с тем же отпечатком обязан быть идемпотентным: те же данные не создают дублей.
   */
  requestDigest: string;
  startedAt: string;
  finishedAt?: string | null;
  created?: number | null;
  updated?: number | null;
  skipped?: number | null;
  blocked?: number | null;
  /**
   * Текст ошибки после редакции секретов. Токен и заголовки авторизации сюда не попадают.
   */
  message?: string | null;
  artifactPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Фактические даты выхода эпизодов. Общие для всех сайтов: расписание — это факт, а не редакционный материал конкретного сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "release-events".
 */
export interface ReleaseEvent {
  id: number;
  label: string;
  title: number | Title;
  episode?: (number | null) | Episode;
  airsAt: string;
  state: 'announced' | 'released' | 'delayed' | 'cancelled';
  /**
   * Неизвестную дату нельзя показывать как точную: это выдуманный факт.
   */
  precision: 'exact' | 'day' | 'week' | 'unknown';
  updatedAt: string;
  createdAt: string;
}
/**
 * Параметры встраивания плеера для этого сайта. Значения publisher ID и API-токена здесь НЕ хранятся: указывается только имя секрета (secret_ref), значение подставляет сервер.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-profiles".
 */
export interface PlayerProfile {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Например PLAYER_PUBLISHER_ID_SITE_A. В CMS и git хранится только имя переменной; значение подставляет сервер. Само значение — публичный параметр встраивания: по контракту оно обязано быть в HTML как data-publisher-id. Секретом является токен Content API, а не этот идентификатор.
   */
  publisherIdRef: string;
  /**
   * Только значения из документированного контракта плеера.
   */
  aggregator: 'kp' | 'mali' | 'mdl';
  showBanner?: boolean | null;
  showVoiceOnly?: boolean | null;
  /**
   * Передаётся в плеер только если у озвучки заполнено значение контракта.
   */
  priorityVoice?: (number | null) | Voice;
  /**
   * disable-licensed="false" в production неизменно и задаётся кодом, а не этой формой. Попытка отправить иное значение — BLOCKED_PLAYER_CONTRACT.
   */
  contractNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Название, контакты, правила комментариев и SEO-умолчания одного сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Заполняется из пакета сайта. Пустое поле не заменяется придуманным брендом: это BLOCKED_INPUT, а не повод сочинить название.
   */
  siteName: string;
  tagline?: string | null;
  /**
   * Например: «{page} — {site}». Подставляются только фактические значения страницы.
   */
  seoTitleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  commentsEnabled?: boolean | null;
  /**
   * Выключение премодерации — решение владельца сайта, оно фиксируется в пакете сайта.
   */
  premoderation?: boolean | null;
  minIntervalSeconds?: number | null;
  maxLength?: number | null;
  /**
   * Показывается рядом с формой. Текст собственный, не скопированный.
   */
  rulesText?: string | null;
  legalPages?: (number | Page)[] | null;
  /**
   * Обязательно описывает происхождение материалов и порядок обращения правообладателя.
   */
  rightsNotice?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Меню в шапке и подвале. Ссылки ведут только на страницы этого сайта или явно помеченные внешние.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  tenant?: (number | null) | Tenant;
  label?: string | null;
  header?:
    | {
        title: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerGroups?:
    | {
        title: string;
        links?:
          | {
              title: string;
              href: string;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Состав и порядок блоков главной. Блоки включаются флажком и переставляются перетаскиванием: порядок в списке — это порядок на странице.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-layout".
 */
export interface HomeLayout {
  id: number;
  tenant?: (number | null) | Tenant;
  label?: string | null;
  blocks?:
    | (
        | {
            enabled?: boolean | null;
            heading?: string | null;
            items?: (number | TenantTitle)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSpotlight';
          }
        | {
            enabled?: boolean | null;
            heading?: string | null;
            days?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'releaseSchedule';
          }
        | {
            enabled?: boolean | null;
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestUpdates';
          }
        | {
            enabled?: boolean | null;
            heading?: string | null;
            collections?: (number | EditorialCollection)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorialPicks';
          }
        | {
            enabled?: boolean | null;
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsFeed';
          }
        | {
            enabled?: boolean | null;
            genres?: (number | Genre)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genreRails';
          }
        | {
            enabled?: boolean | null;
            heading?: string | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'catalog-media';
        value: number | CatalogMedia;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'studios';
        value: number | Studio;
      } | null)
    | ({
        relationTo: 'titles';
        value: number | Title;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'episodes';
        value: number | Episode;
      } | null)
    | ({
        relationTo: 'voices';
        value: number | Voice;
      } | null)
    | ({
        relationTo: 'rights-records';
        value: number | RightsRecord;
      } | null)
    | ({
        relationTo: 'source-records';
        value: number | SourceRecord;
      } | null)
    | ({
        relationTo: 'tenant-titles';
        value: number | TenantTitle;
      } | null)
    | ({
        relationTo: 'editorial-collections';
        value: number | EditorialCollection;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'comment-reports';
        value: number | CommentReport;
      } | null)
    | ({
        relationTo: 'import-jobs';
        value: number | ImportJob;
      } | null)
    | ({
        relationTo: 'release-events';
        value: number | ReleaseEvent;
      } | null)
    | ({
        relationTo: 'player-profiles';
        value: number | PlayerProfile;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'home-layout';
        value: number | HomeLayout;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  seoProfile?: T;
  theme?: T;
  indexingEnabled?: T;
  allowGuestComments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-media_select".
 */
export interface CatalogMediaSelect<T extends boolean = true> {
  alt?: T;
  rightsRecord?: T;
  source?: T;
  sourceRef?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studios_select".
 */
export interface StudiosSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  source?: T;
  sourceRef?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "titles_select".
 */
export interface TitlesSelect<T extends boolean = true> {
  primaryName?: T;
  englishName?: T;
  originalName?: T;
  alternativeNames?:
    | T
    | {
        value?: T;
        id?: T;
      };
  kind?: T;
  status?: T;
  year?: T;
  factualSynopsis?: T;
  availability?: T;
  genres?: T;
  studios?: T;
  poster?: T;
  playbackAggregator?: T;
  playbackTitleId?: T;
  rightsRecord?: T;
  relatedTitles?: T;
  source?: T;
  sourceRef?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  title?: T;
  number?: T;
  label?: T;
  source?: T;
  sourceRef?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  season?: T;
  number?: T;
  label?: T;
  airedAt?: T;
  playbackAvailable?: T;
  source?: T;
  sourceRef?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voices_select".
 */
export interface VoicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  playerValue?: T;
  source?: T;
  sourceRef?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rights-records_select".
 */
export interface RightsRecordsSelect<T extends boolean = true> {
  label?: T;
  holder?: T;
  contractRef?: T;
  territory?: T;
  validUntil?: T;
  allowsPublication?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-records_select".
 */
export interface SourceRecordsSelect<T extends boolean = true> {
  label?: T;
  kind?: T;
  reference?: T;
  sha256?: T;
  retrievedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-titles_select".
 */
export interface TenantTitlesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  editorialIntro?: T;
  editorialAuthor?: T;
  highlight?: T;
  seoTitle?: T;
  seoDescription?: T;
  robots?: T;
  canonicalOverride?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-collections_select".
 */
export interface EditorialCollectionsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  intro?: T;
  items?: T;
  seoTitle?: T;
  seoDescription?: T;
  robots?: T;
  canonicalOverride?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  headline?: T;
  slug?: T;
  lead?: T;
  body?: T;
  author?: T;
  publishedAt?: T;
  cover?: T;
  seoTitle?: T;
  seoDescription?: T;
  robots?: T;
  canonicalOverride?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  body?: T;
  seoTitle?: T;
  seoDescription?: T;
  robots?: T;
  canonicalOverride?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  rightsRecord?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  tenant?: T;
  from?: T;
  to?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  tenant?: T;
  summary?: T;
  actor?: T;
  collection?: T;
  documentId?: T;
  before?: T;
  after?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  tenant?: T;
  targetType?: T;
  targetId?: T;
  targetUrl?: T;
  author?: T;
  guestName?: T;
  guestEmail?: T;
  parent?: T;
  root?: T;
  depth?: T;
  body?: T;
  excerpt?: T;
  status?: T;
  moderator?: T;
  moderatedAt?: T;
  moderatorNote?: T;
  reportCount?: T;
  submissionKey?: T;
  authorKey?: T;
  submissionMeta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comment-reports_select".
 */
export interface CommentReportsSelect<T extends boolean = true> {
  tenant?: T;
  comment?: T;
  reason?: T;
  note?: T;
  resolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs_select".
 */
export interface ImportJobsSelect<T extends boolean = true> {
  reference?: T;
  mode?: T;
  status?: T;
  requestDigest?: T;
  startedAt?: T;
  finishedAt?: T;
  created?: T;
  updated?: T;
  skipped?: T;
  blocked?: T;
  message?: T;
  artifactPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "release-events_select".
 */
export interface ReleaseEventsSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  episode?: T;
  airsAt?: T;
  state?: T;
  precision?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-profiles_select".
 */
export interface PlayerProfilesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  publisherIdRef?: T;
  aggregator?: T;
  showBanner?: T;
  showVoiceOnly?: T;
  priorityVoice?: T;
  contractNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  siteName?: T;
  tagline?: T;
  seoTitleTemplate?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  commentsEnabled?: T;
  premoderation?: T;
  minIntervalSeconds?: T;
  maxLength?: T;
  rulesText?: T;
  legalPages?: T;
  rightsNotice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  header?:
    | T
    | {
        title?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  footerGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              title?: T;
              href?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-layout_select".
 */
export interface HomeLayoutSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  blocks?:
    | T
    | {
        heroSpotlight?:
          | T
          | {
              enabled?: T;
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        releaseSchedule?:
          | T
          | {
              enabled?: T;
              heading?: T;
              days?: T;
              id?: T;
              blockName?: T;
            };
        latestUpdates?:
          | T
          | {
              enabled?: T;
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        editorialPicks?:
          | T
          | {
              enabled?: T;
              heading?: T;
              collections?: T;
              id?: T;
              blockName?: T;
            };
        newsFeed?:
          | T
          | {
              enabled?: T;
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        genreRails?:
          | T
          | {
              enabled?: T;
              genres?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              enabled?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'tenant-titles';
          value: number | TenantTitle;
        } | null)
      | ({
          relationTo: 'editorial-collections';
          value: number | EditorialCollection;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}