#!/usr/bin/env bash
# Record the result of a full verification run as a committed artifact.
#
#   record-evidence.sh           regenerate docs/verification/latest-run.md
#   record-evidence.sh --check   fail if the committed record disagrees with a
#                                fresh run (used by CI to catch stale evidence)
#
# Only the stage verdicts are compared, not timestamps or commit hashes, so the
# check is stable across runs while still catching a stage that changed result.
set -uo pipefail

cd "$(dirname "$0")/.."

REPORT="docs/verification/latest-run.md"
MODE="${1:-write}"

RAW="$(./scripts/verify.sh 2>&1)"
STATUS=$?

VERDICTS="$(echo "$RAW" | grep -E '^(PASS|FAIL): ' | sort)"

if [ "$MODE" = "--check" ]; then
  if [ ! -f "$REPORT" ]; then
    echo "No committed evidence at $REPORT" >&2
    exit 1
  fi
  # Read only the verdict section. The full-output block below it repeats the
  # same lines, so grepping the whole file would double-count them.
  COMMITTED="$(sed -n '/^## Stage verdicts$/,/^## Full output$/p' "$REPORT" \
    | grep -E '^(PASS|FAIL): ' | sort)"
  if [ "$VERDICTS" != "$COMMITTED" ]; then
    echo "Committed evidence is stale. Fresh run differs from $REPORT:" >&2
    diff <(echo "$COMMITTED") <(echo "$VERDICTS") >&2 || true
    echo "Regenerate with: ./scripts/record-evidence.sh" >&2
    exit 1
  fi
  echo "Committed evidence matches a fresh run."
  exit $STATUS
fi

mkdir -p "$(dirname "$REPORT")"

{
  echo "# Verification evidence"
  echo
  echo "Generated by \`scripts/record-evidence.sh\`. Do not edit by hand."
  echo
  echo "| Field | Value |"
  echo "| --- | --- |"
  echo "| Branch | \`$(git rev-parse --abbrev-ref HEAD)\` |"
  echo "| Commit at time of run | \`$(git rev-parse HEAD)\` |"
  echo "| Recorded at | $(date -u +%Y-%m-%dT%H:%M:%SZ) |"
  echo "| Stages failed | ${STATUS} |"
  echo
  echo "## Stage verdicts"
  echo
  echo "$VERDICTS"
  echo
  echo "## Full output"
  echo
  echo '```'
  echo "$RAW"
  echo '```'
} > "$REPORT"

echo "Wrote $REPORT (failed stages: ${STATUS})"
exit $STATUS
